/*this file is auto generated by rules.mk from config.mk*/
#ifndef __libzlt_CONFIG_H
#define __libzlt_CONFIG_H

#define ARCH_X86 1
/*no define ARCH_ARM */
/*no define ARCH_UNI */
/*no define ARCH_MIPS */
/*no define ARCH_X86_64 */
/*no define ARCH_BF */
#define SYS_LINUX 1
/*no define SYS_VXWORKS */
/*no define SYS_CYGWIN */
/*no define SYS_ANDROID */
/*no define USE_FLOAT_AS_TFLOAT */
#define HAVE_THREAD_SUPPORT 1
#define HAVE_EPOLL 1

#endif

